# nacos 配置
host: "192.168.171.223"
port: 8848
namespace: '0acc94cf-4d1b-4be7-8f90-b651b3049e33'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'dev'


#
#name: 'user-web'
#port: 8021
#user_srv:
#  host: '10.112.51.198'
#  port: 50051
#  name: 'user-srv'
#
#jwt:
#  key: 'H0!!IplcbiaZA!tSr#O%KavAz3*ZqLAl'
#
#sms:
#  key: ''
#  secrect: ''
#  expire: 300
#
#redis:
#  host: '59.110.216.174'
#  port: 6379
#
#consul:
#  host: '192.168.171.223'
#  port: 8500
