name: 'user-web'
port: 8021
user_srv:
  host: '127.0.0.1'
  port: 50051

jwt:
  key: 'H0!!IplcbiaZA!tSr#O%KavAz3*ZqLAl'

sms:
  key: ''
  secrect: ''
  expire: 300

redis:
  host: '59.110.216.174'
  port: 6379
